# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6fa50064b319db25872aaccbbf73eb33d927164cc03574361100ad304907e9b2bc615385a947a496379504f1e68dcc79a3a72c8706931cc1ed24f7548e325773

test:
  secret_key_base: b668d9e4ce3b7b34080c850b48768ed219a2dc45770f8eb125ba69a20128f9ad30522ae581a5f411ca32566e8bb5353c0293c66c425fc3fb873259da7f70be86

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
